### ISSUE TITLE
[HCA DB] Download project matrices

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#693]
```[tasklist]
### Tasks
- [ ] https://github.com/clevercanary/data-browser/issues/697
- [ ] https://github.com/clevercanary/data-browser/issues/698
- [ ] https://github.com/clevercanary/data-browser/issues/699
- [ ] https://github.com/clevercanary/data-browser/issues/700
- [ ] https://github.com/clevercanary/data-browser/issues/701
- [ ] https://github.com/clevercanary/data-browser/issues/706
- [ ] https://github.com/clevercanary/data-browser/issues/719
- [ ] https://github.com/clevercanary/data-browser/issues/695
- [ ] https://github.com/clevercanary/data-browser/issues/720
- [ ] https://github.com/clevercanary/data-browser/issues/726
- [ ] https://github.com/clevercanary/data-browser/issues/727
- [ ] https://github.com/clevercanary/data-browser/issues/729
- [ ] https://github.com/clevercanary/data-browser/issues/730
- [ ] https://github.com/clevercanary/data-browser/issues/731
```

**Comment by MillenniumFalconMechanic** [comment]
Completed.
