### ISSUE TITLE
[AnVIL Catalog] Add consent code description to AnVIL portal workspaces descriptions

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#708]
- [x] Do we have mocks for this @frano-m 
- [x] Is the required information in the workspaces.json, or do we need to add it in?

```[tasklist]
### Tasks
- [ ] https://github.com/clevercanary/cc-design/issues/23
- [x] [AnVIL Catalog] On the study list and detail pages, add consent code on a (standard) tooltip when there is no NTag
- [x] [AnVIL Catalog] On the workspaces list, add consent code on a (standard) tooltip when there is no NTag
- [x] [AnVIL Catalog] On the consortia list and detail pages, add consent code on a (standard) tooltip when there is no NTag
```

**Comment by NoopDog** [comment]
@frano-m can you see if we have mocks for this and link them?

**Comment by frano-m** [comment]
@NoopDog I can't seem to locate any mocks for consent code descriptions. We have a standard tooltip which may suffice (if you wish for the descriptions to be in a tooltip)?

We will need to add the description field to the out file

**Comment by MillenniumFalconMechanic** [comment]
Completed.
